services:

  postgres:
    image: postgres:16-alpine
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sindhu@999
      POSTGRES_DB: user_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_management"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build: ./BackEnd
    container_name: db-migrator
    command: npm run migrate
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Sindhu@999
      DB_NAME: user_management
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build: ./BackEnd
    container_name: backend
    ports:
      - "3002:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Sindhu@999
      DB_NAME: user_management
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./FrontEnd/my-app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: